# Generated by Django 3.0.5 on 2020-05-30 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='callagain',
            field=models.ForeignKey(blank=True, help_text='Call again message', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='callagain_label', to='service_development.VoiceLabel', verbose_name='Call again'),
        ),
        migrations.AddField(
            model_name='language',
            name='reasonfail',
            field=models.ForeignKey(blank=True, help_text='Authentication reason for failure message', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reasonfail_label', to='service_development.VoiceLabel', verbose_name='Authentication fail reason'),
        ),
    ]
