# Generated by Django 3.0.5 on 2020-05-18 16:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasadakauser',
            name='_password',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='kasadakauser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username'),
        ),
    ]
