# Generated by Django 3.0.5 on 2020-06-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0002_auto_20200530_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name': 'Risk',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('_percentage_severe', models.PositiveIntegerField(blank=True, help_text='The percentage of people with severe COVID-19 reporting the symptom.', null=True)),
                ('_percentage_nonsevere', models.PositiveIntegerField(blank=True, help_text='The percentage of people with non-severe COVID-19 reporting the symptom.', null=True)),
            ],
            options={
                'verbose_name': 'Symptom',
            },
        ),
    ]
