# Generated by Django 3.0.5 on 2020-05-18 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0002_auto_20200518_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='authenticate',
            field=models.ForeignKey(blank=True, help_text='The fragment that will begin the authentication process', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auth_voice_label', to='service_development.VoiceLabel', verbose_name='Authenticate voice label'),
        ),
        migrations.AddField(
            model_name='language',
            name='next',
            field=models.ForeignKey(blank=True, help_text='Next form field', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_voice_label', to='service_development.VoiceLabel', verbose_name='Next voice label'),
        ),
        migrations.AddField(
            model_name='language',
            name='password',
            field=models.ForeignKey(blank=True, help_text='The fragment that is to be played during authentication, when asking for the password', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='password_voice_label', to='service_development.VoiceLabel', verbose_name='Password voice label'),
        ),
        migrations.AddField(
            model_name='language',
            name='username',
            field=models.ForeignKey(blank=True, help_text='The fragment that is to be played during authentication, when asking for the username', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='username_voice_label', to='service_development.VoiceLabel', verbose_name='Username voice label'),
        ),
    ]
