# Generated by Django 3.0.5 on 2020-05-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0003_auto_20200518_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceservice',
            name='is_pass_based_auth',
            field=models.BooleanField(default=False, help_text='A voice service that has password-based authentication will identify users by asking for their credentials (username and password).', verbose_name='Password-based authentication'),
        ),
        migrations.AlterField(
            model_name='voiceservice',
            name='active',
            field=models.BooleanField(help_text='A voice service that is active is accessible to users. Marking this service as active (which is only possible when it is valid) will activate this service and deactivate all other services.', verbose_name='Voice service active'),
        ),
    ]
