# Generated by Django 3.0.5 on 2020-05-20 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0004_auto_20200519_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='authfail',
            field=models.ForeignKey(blank=True, help_text='Authentication failure message', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authfail_label', to='service_development.VoiceLabel', verbose_name='Authentication fail label'),
        ),
        migrations.AddField(
            model_name='language',
            name='authsuccess',
            field=models.ForeignKey(blank=True, help_text='Authentication success message', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authsuccess_label', to='service_development.VoiceLabel', verbose_name='Authentication success label'),
        ),
    ]
