# Generated by Django 3.0.5 on 2020-06-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0004_selfcheckitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selfcheckitem',
            options={'verbose_name': 'Self-Checks'},
        ),
        migrations.AddField(
            model_name='choice',
            name='read_choiceoptions',
            field=models.BooleanField(default=True, help_text='Whether the choice options should be mentioned to the user for the choice element', verbose_name='Skip Mentioning Choice Options'),
        ),
    ]
