# Generated by Django 3.0.5 on 2020-06-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0005_auto_20200601_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selfcheckitem',
            options={'verbose_name': 'Self-Check'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='read_choiceoptions',
        ),
        migrations.AddField(
            model_name='choice',
            name='skip_reading_choice_options',
            field=models.BooleanField(default=False, help_text='Whether the choice options should be mentioned to the user for the choice element', verbose_name='Skip Mentioning Choice Options'),
        ),
    ]
