# Generated by Django 3.0.5 on 2020-06-01 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0006_auto_20200601_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='_percentage_nonsevere',
            field=models.FloatField(blank=True, help_text='The percentage of people with non-severe COVID-19 reporting the symptom.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='_percentage_severe',
            field=models.FloatField(blank=True, help_text='The percentage of people with severe COVID-19 reporting the symptom.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
