# Generated by Django 3.0.5 on 2020-06-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0007_auto_20200601_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_persistent_choice',
            field=models.BooleanField(default=False, help_text='Whether the chosen option should be saved in the database', verbose_name='Save Choice Option'),
        ),
    ]
