# Generated by Django 3.0.5 on 2020-06-02 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0009_auto_20200602_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='risk',
            field=models.ForeignKey(blank=True, help_text='Select the corresponding risk, if this choice element represents one', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk', to='service_development.Risk', verbose_name='Associated risk'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='symptom',
            field=models.ForeignKey(blank=True, help_text='Select the corresponding symptom, if this choice element represents one', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='symptom', to='service_development.Symptom', verbose_name='Associated symptom'),
        ),
    ]
