# Generated by Django 3.0.5 on 2020-06-04 18:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0011_auto_20200604_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultUtils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infected_probability_benchmark', models.FloatField(blank=True, help_text='Point of reference against which the infection probability is compared and conclusions may be drawn whether the person is infected or not.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('symptom_no_benchmark', models.PositiveIntegerField(blank=True, help_text='Point of reference against which the number of reported symptoms per session is computed and conclusions may be drawn whether the person is infected or not.', null=True)),
            ],
            options={
                'verbose_name': 'Result Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='messagepresentation',
            name='is_result',
        ),
        migrations.AddField(
            model_name='messagepresentation',
            name='is_result_message',
            field=models.BooleanField(default=False, verbose_name='Whether the element is a result presentation message'),
        ),
        migrations.CreateModel(
            name='ResultItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infected_probability', models.FloatField(blank=True, help_text='The probability that the person is infected', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('symptom_no', models.PositiveIntegerField(blank=True, help_text='The number of reported symptoms in a given session.', null=True)),
                ('risk_no', models.PositiveIntegerField(blank=True, help_text='The number of reported risks in a given session.', null=True)),
                ('is_exposed', models.BooleanField(blank=True, null=True, verbose_name='Whether the person has been exposed.')),
                ('is_infected_predicted', models.BooleanField(blank=True, null=True, verbose_name='Whether the person is believed to have the infection after the self-check.')),
                ('is_infected_confirmed', models.BooleanField(blank=True, null=True, verbose_name='Whether the person was really infected. This field should only be updated after testing has been performed, to confirm or to infirm the predicted result.')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_result', to='service_development.CallSession', verbose_name='Associated call session')),
            ],
            options={
                'verbose_name': 'Result item',
            },
        ),
        migrations.AlterField(
            model_name='messagepresentation',
            name='result',
            field=models.ForeignKey(blank=True, help_text='A message is linked to a result item if the presentation element communicates a self-check result.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result', to='service_development.ResultItem', verbose_name='The associated result item'),
        ),
        migrations.DeleteModel(
            name='ResultMessage',
        ),
    ]
