# Generated by Django 3.0.5 on 2020-06-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0014_auto_20200605_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosisconfigparameters',
            options={'verbose_name_plural': 'Diagnosis Configurable Parameters'},
        ),
        migrations.AlterModelOptions(
            name='selfcheckitem',
            options={'verbose_name_plural': 'Self-Reported Items'},
        ),
    ]
