# Generated by Django 3.0.5 on 2020-06-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0017_auto_20200607_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultconfig',
            options={'verbose_name_plural': 'Result Configuration'},
        ),
    ]
