# Generated by Django 3.0.5 on 2020-06-07 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0019_auto_20200607_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultconfig',
            name='no_testing_voice_label',
        ),
        migrations.RemoveField(
            model_name='resultconfig',
            name='result_negative_voice_label',
        ),
        migrations.RemoveField(
            model_name='resultconfig',
            name='result_positive_voice_label',
        ),
        migrations.RemoveField(
            model_name='resultconfig',
            name='yes_contact_voice_label',
        ),
        migrations.RemoveField(
            model_name='resultconfig',
            name='yes_risks_voice_label',
        ),
        migrations.RemoveField(
            model_name='resultconfig',
            name='yes_testing_voice_label',
        ),
        migrations.AddField(
            model_name='language',
            name='no_testing_voice_label',
            field=models.ForeignKey(blank=True, help_text='A Voice Label for no testing necessary', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='no_testing_voice_label', to='service_development.VoiceLabel', verbose_name='Testing not necessary voice label'),
        ),
        migrations.AddField(
            model_name='language',
            name='result_negative_voice_label',
            field=models.ForeignKey(blank=True, help_text='A Voice Label for negative diagnosis result', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result_negative_voice_label', to='service_development.VoiceLabel', verbose_name='User is not suspect voice label'),
        ),
        migrations.AddField(
            model_name='language',
            name='result_positive_voice_label',
            field=models.ForeignKey(blank=True, help_text='A Voice Label for positive diagnosis result', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='result_positive_voice_label', to='service_development.VoiceLabel', verbose_name='User is suspect voice label'),
        ),
        migrations.AddField(
            model_name='language',
            name='yes_contact_voice_label',
            field=models.ForeignKey(blank=True, help_text='A Voice Label for exposure or contact warning', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yes_contact_voice_label', to='service_development.VoiceLabel', verbose_name='Exposure warning voice label'),
        ),
        migrations.AddField(
            model_name='language',
            name='yes_risks_voice_label',
            field=models.ForeignKey(blank=True, help_text='A Voice Label for risks warning', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yes_risks_voice_label', to='service_development.VoiceLabel', verbose_name='Risks warning voice label'),
        ),
        migrations.AddField(
            model_name='language',
            name='yes_testing_voice_label',
            field=models.ForeignKey(blank=True, help_text='A Voice Label for testing needed', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yes_testing_voice_label', to='service_development.VoiceLabel', verbose_name='Testing recommended voice label'),
        ),
    ]
