# Generated by Django 3.0.5 on 2020-06-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0021_auto_20200608_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultconfig',
            options={'verbose_name_plural': 'Diagnosis Configuration Parameters'},
        ),
        migrations.AlterModelOptions(
            name='resultitem',
            options={'verbose_name_plural': 'Self-Check Results'},
        ),
    ]
