# Generated by Django 3.0.5 on 2020-06-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0022_auto_20200608_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultitem',
            name='testing_confirmation',
            field=models.BooleanField(blank=True, help_text='Whether the person tested positive for COVID-19.', null=True, verbose_name='Predicted result was confirmed by testing'),
        ),
    ]
